apiVersion: v1
kind: Service
metadata:
  labels:
    role: api
    tier: backend
  name: deck
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: deck
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: api
    tier: backend
  name: deck
spec:
  template:
    metadata:
      labels:
        role: api
        tier: backend
    spec:
      containers:
      - image: quay.io/john_mckenzie/deck:v0.0.1
        name: deck
        ports:
        - containerPort: 4778
          name: http
