apiVersion: v1
kind: Service
metadata:
  labels:
    role: client
    tier: frontend
  name: middy
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: middy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: client
    tier: frontend
  name: middy
spec:
  template:
    metadata:
      labels:
        role: client
        tier: frontend
    spec:
      containers:
      - image: quay.io/john_mckenzie/middy:v0.0.1
        name: middy
        env:
        - name: DECK_HOST
          value: deck
        ports:
        - containerPort: 80
          name: http
